import { createContext, useContext, useState, useCallback } from 'react';

const LanguageContext = createContext(null);

// Supported languages with Web Speech API locale codes
export const LANGUAGES = [
  { code: 'en', locale: 'en-IN', label: 'English', native: 'English', flag: '🇬🇧' },
  { code: 'hi', locale: 'hi-IN', label: 'Hindi', native: 'हिन्दी', flag: '🇮🇳' },
  { code: 'ta', locale: 'ta-IN', label: 'Tamil', native: 'தமிழ்', flag: '🇮🇳' },
  { code: 'te', locale: 'te-IN', label: 'Telugu', native: 'తెలుగు', flag: '🇮🇳' },
  { code: 'bn', locale: 'bn-IN', label: 'Bengali', native: 'বাংলা', flag: '🇮🇳' },
  { code: 'mr', locale: 'mr-IN', label: 'Marathi', native: 'मराठी', flag: '🇮🇳' },
  { code: 'gu', locale: 'gu-IN', label: 'Gujarati', native: 'ગુજરાતી', flag: '🇮🇳' },
  { code: 'kn', locale: 'kn-IN', label: 'Kannada', native: 'ಕನ್ನಡ', flag: '🇮🇳' },
];

// ============ TRANSLATIONS ============
const translations = {
  en: {
    // Common
    back: 'Back',
    loading: 'Loading...',
    submit: 'Submit',
    cancel: 'Cancel',
    yes: 'Yes',
    no: 'No',
    or: 'OR',
    save: 'Save',
    
    // Landing
    appName: 'Sehat Saathi',
    appTagline: 'AI-Powered Smart Healthcare for Rural India',
    getStarted: 'Get Started',
    transforming: 'Transforming Rural Healthcare',
    quickDemo: '🚀 Quick Demo Access',
    demoDesc: 'Try any portal instantly with demo credentials',
    patient: 'Patient',
    doctor: 'Doctor',
    pharmacy: 'Pharmacy',
    
    // Features
    aiTriage: 'AI Triage',
    aiTriageDesc: '3-stage symptom assessment with intelligent severity scoring',
    smartQueue: 'Smart Queue',
    smartQueueDesc: 'Predictive wait times with real-time transparency',
    healthRecords: 'Health Records',
    healthRecordsDesc: 'ABHA-linked digital health records with AI wellness tips',
    pharmacyFeature: 'Pharmacy',
    pharmacyDesc: 'Instant prescription routing with stock intelligence',
    heatmap: 'Health Heatmap',
    heatmapDesc: 'Village-level disease surveillance and outbreak alerts',
    aiWellness: 'AI Wellness',
    aiWellnessDesc: 'Personalized health recommendations powered by AI',
    
    // Login
    welcomeBack: 'Welcome Back',
    loginTo: 'Login to Sehat Saathi',
    mobileNumber: 'Mobile Number',
    enterPhone: 'Enter 10-digit number',
    sendOtp: 'Send OTP',
    otpCode: 'OTP Code',
    verify: 'Verify & Login',
    changeNumber: 'Change number',
    demoOtp: '💡 Demo OTP: 123456',
    orUseDemo: 'OR USE DEMO',
    loginAsPatient: '🧑 Login as Patient',
    loginAsDoctor: '🩺 Login as Doctor',
    loginAsPharmacist: '💊 Login as Pharmacist',
    
    // Patient Dashboard
    goodMorning: 'Good Morning',
    goodAfternoon: 'Good Afternoon',
    goodEvening: 'Good Evening',
    queue: 'Queue',
    doctors: 'Doctors',
    alerts: 'Alerts',
    youreInQueue: "You're in queue — Position",
    minWait: 'min wait',
    quickActions: 'Quick Actions',
    startTriage: 'Start Triage',
    aiSymptomAssessment: 'AI symptom assessment',
    queueStatus: 'Queue Status',
    checkPosition: 'Check your position',
    viewRecords: 'View ABHA records',
    bookAppointment: 'Book Appointment',
    scheduleVisit: 'Schedule a visit',
    healthHeatmap: 'Health Heatmap',
    communityAlerts: 'Community health alerts',
    emergencySos: 'Emergency SOS',
    oneTapAmbulance: 'One-tap ambulance',
    
    // Triage
    aiTriageAssessment: 'AI Triage Assessment',
    triageIntro: 'Answer a few questions or speak your symptoms to assess severity.',
    beginAssessment: 'Begin Assessment',
    voiceTriage: '🎤 Voice Triage',
    voiceTriageDesc: 'Speak your symptoms in any language',
    stageOf: 'Stage {0} of 3',
    emergencyScreening: 'Emergency Screening',
    severityAssessment: 'Severity Assessment',
    contextHistory: 'Context & History',
    quickSafety: 'Quick safety check — answer honestly',
    helpUnderstand: 'Help us understand your symptoms',
    fewMoreDetails: 'A few more details for accurate assessment',
    triageComplete: 'Triage Complete',
    viewQueue: 'View Queue',
    dashboard: 'Dashboard',
    nextStage: 'Next Stage',
    completeAssessment: 'Complete Assessment',
    
    // Voice Triage
    speakSymptoms: 'Speak Your Symptoms',
    speakDesc: 'Describe what you are feeling in your own language',
    tapToSpeak: 'Tap to Speak',
    listening: 'Listening...',
    processing: 'Analyzing symptoms...',
    speakNow: 'Speak now — describe your pain, symptoms, or problems',
    detectedSymptoms: 'Detected Symptoms',
    severity: 'Severity',
    painLevel: 'Pain Level',
    duration: 'Duration',
    submitVoiceTriage: 'Submit Voice Assessment',
    tryAgain: 'Try Again',
    noSymptoms: 'No symptoms detected. Please try speaking again.',
    voiceNotSupported: 'Voice input not supported in this browser',
    
    // Heatmap
    villageHealthHeatmap: 'Village Health Heatmap',
    diseaseOutbreak: 'Disease Outbreak Surveillance',
    allSymptoms: 'All Symptoms',
    lowRisk: 'Low Risk',
    mediumRisk: 'Medium Risk',
    highRisk: 'High Risk',
    villages: 'Villages',
    totalCases: 'Total Cases',
    redZones: 'Red Zones',
    villagesBySeverity: 'Villages by Severity',
    cases: 'cases',
    healthAlerts: 'Health Alerts',
    redAlerts: 'Red Alerts',
    warnings: 'Warnings',
    symptomsBreakdown: 'Symptoms Breakdown',
    
    // Doctor
    doctorDashboard: 'Doctor Dashboard',
    callNextPatient: 'Call Next Patient',
    patientQueue: 'Patient Queue',
    refresh: 'Refresh',
    noPatients: 'No patients in queue',
    inConsultation: 'IN CONSULTATION',
    viewBrief: 'View Brief',
    diagnose: 'Diagnose',
    patientBrief: 'Patient Brief',
    startConsultation: 'Start Consultation',
    consultation: 'Consultation',
    diagnosis: 'Diagnosis',
    clinicalNotes: 'Clinical Notes',
    followUpDate: 'Follow-Up Date',
    prescription: 'Prescription',
    addMedicine: '+ Add Medicine',
    completeAndSend: 'Complete & Send Rx',
    
    // Pharmacy
    pharmacyDashboard: 'Pharmacy Dashboard',
    pending: 'Pending',
    dispensed: 'Dispensed',
    lowStock: 'Low Stock',
    rate: 'Rate',
    overview: 'Overview',
    rxQueue: 'Rx Queue',
    inventory: 'Inventory',
    analytics: 'Analytics',
    stockAlerts: 'Stock Alerts',
    outOfStock: 'OUT OF STOCK',
    pendingPrescriptions: 'Pending Prescriptions',
    monthlyPrescriptions: 'Monthly Prescriptions',
    searchMedicines: 'Search medicines...',
    dispensePrescription: 'Dispense Prescription',
    
    // SOS
    emergencyTitle: 'Emergency SOS',
    sosDesc: 'Press the button below to dispatch an ambulance to your location',
    yourInfoShared: 'YOUR INFORMATION WILL BE SHARED',
    name: 'Name',
    bloodGroup: 'Blood Group',
    location: 'Location',
    detecting: 'Detecting...',
    emergencyContacts: 'Emergency Contacts',
    dispatchingAmbulance: 'Dispatching Ambulance...',
    cancelDispatch: 'Tap cancel to abort emergency dispatch',
    ambulanceDispatched: 'Ambulance Dispatched!',
    stayCalmHelp: 'Stay calm. Help is on the way.',
    firstAidTips: 'First Aid Tips',
    
    // Language selector
    selectLanguage: 'Select Language',
    language: 'Language',
  },
  
  hi: {
    back: 'वापस',
    loading: 'लोड हो रहा है...',
    submit: 'जमा करें',
    cancel: 'रद्द करें',
    yes: 'हां',
    no: 'नहीं',
    or: 'या',
    save: 'सहेजें',
    appName: 'सेहत साथी',
    appTagline: 'ग्रामीण भारत के लिए AI-संचालित स्मार्ट हेल्थकेयर',
    getStarted: 'शुरू करें',
    transforming: 'ग्रामीण स्वास्थ्य सेवा में बदलाव',
    quickDemo: '🚀 त्वरित डेमो एक्सेस',
    demoDesc: 'डेमो क्रेडेंशियल्स के साथ तुरंत किसी भी पोर्टल को आज़माएं',
    patient: 'रोगी',
    doctor: 'डॉक्टर',
    pharmacy: 'फार्मेसी',
    aiTriage: 'AI ट्राइएज',
    aiTriageDesc: '3-चरण लक्षण मूल्यांकन',
    smartQueue: 'स्मार्ट कतार',
    smartQueueDesc: 'रियल-टाइम पारदर्शिता के साथ अनुमानित प्रतीक्षा समय',
    healthRecords: 'स्वास्थ्य रिकॉर्ड',
    healthRecordsDesc: 'ABHA-लिंक्ड डिजिटल स्वास्थ्य रिकॉर्ड',
    pharmacyFeature: 'फार्मेसी',
    pharmacyDesc: 'स्टॉक इंटेलिजेंस के साथ तत्काल प्रिस्क्रिप्शन रूटिंग',
    heatmap: 'स्वास्थ्य हीटमैप',
    heatmapDesc: 'गांव-स्तरीय रोग निगरानी और प्रकोप अलर्ट',
    aiWellness: 'AI वेलनेस',
    aiWellnessDesc: 'व्यक्तिगत स्वास्थ्य सिफारिशें',
    welcomeBack: 'वापस स्वागत है',
    loginTo: 'सेहत साथी में लॉगिन करें',
    mobileNumber: 'मोबाइल नंबर',
    enterPhone: '10-अंकीय नंबर दर्ज करें',
    sendOtp: 'OTP भेजें',
    otpCode: 'OTP कोड',
    verify: 'सत्यापित करें और लॉगिन करें',
    changeNumber: 'नंबर बदलें',
    demoOtp: '💡 डेमो OTP: 123456',
    orUseDemo: 'या डेमो उपयोग करें',
    loginAsPatient: '🧑 रोगी के रूप में लॉगिन',
    loginAsDoctor: '🩺 डॉक्टर के रूप में लॉगिन',
    loginAsPharmacist: '💊 फार्मासिस्ट के रूप में लॉगिन',
    goodMorning: 'सुप्रभात',
    goodAfternoon: 'शुभ दोपहर',
    goodEvening: 'शुभ संध्या',
    queue: 'कतार',
    doctors: 'डॉक्टर',
    alerts: 'अलर्ट',
    youreInQueue: 'आप कतार में हैं — स्थिति',
    minWait: 'मिनट प्रतीक्षा',
    quickActions: 'त्वरित क्रियाएं',
    startTriage: 'ट्राइएज शुरू करें',
    aiSymptomAssessment: 'AI लक्षण मूल्यांकन',
    queueStatus: 'कतार स्थिति',
    checkPosition: 'अपनी स्थिति जांचें',
    viewRecords: 'ABHA रिकॉर्ड देखें',
    bookAppointment: 'अपॉइंटमेंट बुक करें',
    scheduleVisit: 'अपनी अगली विज़िट शेड्यूल करें',
    healthHeatmap: 'स्वास्थ्य हीटमैप',
    communityAlerts: 'सामुदायिक स्वास्थ्य अलर्ट',
    emergencySos: 'आपातकालीन SOS',
    oneTapAmbulance: 'एक-टैप एम्बुलेंस',
    aiTriageAssessment: 'AI ट्राइएज मूल्यांकन',
    triageIntro: 'कुछ सवालों का जवाब दें या अपने लक्षण बोलकर बताएं।',
    beginAssessment: 'मूल्यांकन शुरू करें',
    voiceTriage: '🎤 वॉइस ट्राइएज',
    voiceTriageDesc: 'किसी भी भाषा में अपने लक्षण बोलें',
    stageOf: 'चरण {0} / 3',
    emergencyScreening: 'आपातकालीन जांच',
    severityAssessment: 'गंभीरता मूल्यांकन',
    contextHistory: 'संदर्भ और इतिहास',
    quickSafety: 'त्वरित सुरक्षा जांच',
    helpUnderstand: 'अपने लक्षणों को समझने में मदद करें',
    fewMoreDetails: 'सटीक मूल्यांकन के लिए कुछ और विवरण',
    triageComplete: 'ट्राइएज पूर्ण',
    viewQueue: 'कतार देखें',
    dashboard: 'डैशबोर्ड',
    nextStage: 'अगला चरण',
    completeAssessment: 'मूल्यांकन पूर्ण करें',
    speakSymptoms: 'अपने लक्षण बोलें',
    speakDesc: 'अपनी भाषा में बताएं कि आपको क्या तकलीफ है',
    tapToSpeak: 'बोलने के लिए टैप करें',
    listening: 'सुन रहे हैं...',
    processing: 'लक्षणों का विश्लेषण...',
    speakNow: 'अभी बोलें — अपना दर्द, लक्षण या समस्या बताएं',
    detectedSymptoms: 'पहचाने गए लक्षण',
    severity: 'गंभीरता',
    painLevel: 'दर्द का स्तर',
    duration: 'अवधि',
    submitVoiceTriage: 'वॉइस मूल्यांकन जमा करें',
    tryAgain: 'पुनः प्रयास करें',
    noSymptoms: 'कोई लक्षण नहीं पाया गया। कृपया फिर से बोलें।',
    voiceNotSupported: 'इस ब्राउज़र में वॉइस इनपुट समर्थित नहीं है',
    villageHealthHeatmap: 'गांव स्वास्थ्य हीटमैप',
    diseaseOutbreak: 'रोग प्रकोप निगरानी',
    allSymptoms: 'सभी लक्षण',
    lowRisk: 'कम जोखिम',
    mediumRisk: 'मध्यम जोखिम',
    highRisk: 'उच्च जोखिम',
    villages: 'गांव',
    totalCases: 'कुल मामले',
    redZones: 'रेड ज़ोन',
    villagesBySeverity: 'गंभीरता के अनुसार गांव',
    cases: 'मामले',
    healthAlerts: 'स्वास्थ्य अलर्ट',
    redAlerts: 'रेड अलर्ट',
    warnings: 'चेतावनियां',
    symptomsBreakdown: 'लक्षण विवरण',
    doctorDashboard: 'डॉक्टर डैशबोर्ड',
    callNextPatient: 'अगले रोगी को बुलाएं',
    patientQueue: 'रोगी कतार',
    refresh: 'रिफ्रेश',
    noPatients: 'कतार में कोई रोगी नहीं',
    inConsultation: 'परामर्श में',
    viewBrief: 'ब्रीफ देखें',
    diagnose: 'निदान',
    patientBrief: 'रोगी ब्रीफ',
    startConsultation: 'परामर्श शुरू करें',
    consultation: 'परामर्श',
    diagnosis: 'निदान',
    clinicalNotes: 'नैदानिक नोट्स',
    followUpDate: 'फॉलो-अप तिथि',
    prescription: 'नुस्खा',
    addMedicine: '+ दवा जोड़ें',
    completeAndSend: 'पूर्ण करें और Rx भेजें',
    pharmacyDashboard: 'फार्मेसी डैशबोर्ड',
    pending: 'लंबित',
    dispensed: 'वितरित',
    lowStock: 'कम स्टॉक',
    rate: 'दर',
    overview: 'अवलोकन',
    rxQueue: 'Rx कतार',
    inventory: 'इन्वेंटरी',
    analytics: 'विश्लेषण',
    stockAlerts: 'स्टॉक अलर्ट',
    outOfStock: 'स्टॉक में नहीं',
    pendingPrescriptions: 'लंबित नुस्खे',
    monthlyPrescriptions: 'मासिक नुस्खे',
    searchMedicines: 'दवाइयां खोजें...',
    dispensePrescription: 'नुस्खा वितरित करें',
    emergencyTitle: 'आपातकालीन SOS',
    sosDesc: 'एम्बुलेंस भेजने के लिए नीचे दिया गया बटन दबाएं',
    yourInfoShared: 'आपकी जानकारी साझा की जाएगी',
    name: 'नाम',
    bloodGroup: 'रक्त समूह',
    location: 'स्थान',
    detecting: 'खोज रहे हैं...',
    emergencyContacts: 'आपातकालीन संपर्क',
    dispatchingAmbulance: 'एम्बुलेंस भेजी जा रही है...',
    cancelDispatch: 'रद्द करने के लिए टैप करें',
    ambulanceDispatched: 'एम्बुलेंस भेज दी गई!',
    stayCalmHelp: 'शांत रहें। मदद आ रही है।',
    firstAidTips: 'प्राथमिक चिकित्सा सुझाव',
    selectLanguage: 'भाषा चुनें',
    language: 'भाषा',
  },

  ta: {
    back: 'பின்',
    loading: 'ஏற்றுகிறது...',
    submit: 'சமர்ப்பிக்க',
    cancel: 'ரத்து',
    yes: 'ஆம்',
    no: 'இல்லை',
    appName: 'சேகத் சாத்தி',
    appTagline: 'கிராமப்புற இந்தியாவுக்கான AI சுகாதாரம்',
    getStarted: 'தொடங்கவும்',
    quickActions: 'விரைவு செயல்கள்',
    startTriage: 'தீவிர பரிசோதனை தொடங்கு',
    voiceTriage: '🎤 குரல் பரிசோதனை',
    voiceTriageDesc: 'உங்கள் மொழியில் அறிகுறிகளைச் சொல்லுங்கள்',
    speakSymptoms: 'உங்கள் அறிகுறிகளைச் சொல்லுங்கள்',
    speakDesc: 'உங்கள் மொழியில் என்ன வலிக்கிறது என்று சொல்லுங்கள்',
    tapToSpeak: 'பேச தட்டவும்',
    listening: 'கேட்கிறது...',
    processing: 'அறிகுறிகளை பகுப்பாய்வு செய்கிறது...',
    detectedSymptoms: 'கண்டறியப்பட்ட அறிகுறிகள்',
    submitVoiceTriage: 'குரல் மதிப்பீட்டை சமர்ப்பிக்கவும்',
    tryAgain: 'மீண்டும் முயற்சிக்கவும்',
    villageHealthHeatmap: 'கிராம சுகாதார வெப்ப வரைபடம்',
    diseaseOutbreak: 'நோய் பரவல் கண்காணிப்பு',
    selectLanguage: 'மொழி தேர்ந்தெடுக்கவும்',
    language: 'மொழி',
    emergencySos: 'அவசர SOS',
    healthRecords: 'சுகாதார பதிவுகள்',
    bookAppointment: 'சந்திப்பு முன்பதிவு',
    queueStatus: 'வரிசை நிலை',
    dashboard: 'டாஷ்போர்டு',
  },

  te: {
    back: 'వెనుకకు',
    loading: 'లోడ్ అవుతోంది...',
    submit: 'సమర్పించు',
    cancel: 'రద్దు',
    yes: 'అవును',
    no: 'కాదు',
    appName: 'సేహత్ సాథీ',
    appTagline: 'గ్రామీణ భారతదేశం కోసం AI ఆరోగ్య సంరక్షణ',
    getStarted: 'ప్రారంభించండి',
    quickActions: 'త్వరిత చర్యలు',
    startTriage: 'ట్రయేజ్ ప్రారంభించండి',
    voiceTriage: '🎤 వాయిస్ ట్రయేజ్',
    voiceTriageDesc: 'మీ భాషలో మీ లక్షణాలను చెప్పండి',
    speakSymptoms: 'మీ లక్షణాలను చెప్పండి',
    speakDesc: 'మీ భాషలో మీకు ఏమి నొప్పి ఉంటుందో చెప్పండి',
    tapToSpeak: 'మాట్లాడటానికి నొక్కండి',
    listening: 'వింటోంది...',
    processing: 'లక్షణాలను విశ్లేషిస్తోంది...',
    detectedSymptoms: 'గుర్తించిన లక్షణాలు',
    submitVoiceTriage: 'వాయిస్ అంచనా సమర్పించండి',
    tryAgain: 'మళ్ళీ ప్రయత్నించండి',
    villageHealthHeatmap: 'గ్రామ ఆరోగ్య హీట్‌మ్యాప్',
    selectLanguage: 'భాషను ఎంచుకోండి',
    language: 'భాష',
    emergencySos: 'అత్యవసర SOS',
    dashboard: 'డాష్‌బోర్డ్',
  },

  bn: {
    back: 'পিছনে',
    loading: 'লোড হচ্ছে...',
    submit: 'জমা দিন',
    cancel: 'বাতিল',
    yes: 'হ্যাঁ',
    no: 'না',
    appName: 'সেহত সাথী',
    appTagline: 'গ্রামীণ ভারতের জন্য AI স্বাস্থ্যসেবা',
    getStarted: 'শুরু করুন',
    quickActions: 'দ্রুত পদক্ষেপ',
    startTriage: 'ট্রায়াজ শুরু করুন',
    voiceTriage: '🎤 ভয়েস ট্রায়াজ',
    voiceTriageDesc: 'আপনার ভাষায় লক্ষণ বলুন',
    speakSymptoms: 'আপনার লক্ষণ বলুন',
    speakDesc: 'আপনার ভাষায় আপনার কষ্ট বলুন',
    tapToSpeak: 'কথা বলতে ট্যাপ করুন',
    listening: 'শুনছি...',
    processing: 'লক্ষণ বিশ্লেষণ করছি...',
    detectedSymptoms: 'সনাক্তকৃত লক্ষণ',
    submitVoiceTriage: 'ভয়েস মূল্যায়ন জমা দিন',
    tryAgain: 'আবার চেষ্টা করুন',
    villageHealthHeatmap: 'গ্রাম স্বাস্থ্য হিটম্যাপ',
    selectLanguage: 'ভাষা নির্বাচন করুন',
    language: 'ভাষা',
    emergencySos: 'জরুরি SOS',
    dashboard: 'ড্যাশবোর্ড',
  },

  mr: {
    back: 'मागे',
    loading: 'लोड होत आहे...',
    submit: 'सबमिट करा',
    cancel: 'रद्द करा',
    yes: 'हो',
    no: 'नाही',
    appName: 'सेहत साथी',
    appTagline: 'ग्रामीण भारतासाठी AI आरोग्य सेवा',
    getStarted: 'सुरू करा',
    quickActions: 'जलद क्रिया',
    startTriage: 'ट्रायएज सुरू करा',
    voiceTriage: '🎤 व्हॉइस ट्रायएज',
    voiceTriageDesc: 'तुमच्या भाषेत लक्षणे सांगा',
    speakSymptoms: 'तुमची लक्षणे सांगा',
    speakDesc: 'तुमच्या भाषेत तुम्हाला काय त्रास होतो ते सांगा',
    tapToSpeak: 'बोलण्यासाठी टॅप करा',
    listening: 'ऐकत आहे...',
    processing: 'लक्षणांचे विश्लेषण...',
    detectedSymptoms: 'शोधलेली लक्षणे',
    submitVoiceTriage: 'व्हॉइस मूल्यांकन सबमिट करा',
    tryAgain: 'पुन्हा प्रयत्न करा',
    villageHealthHeatmap: 'गाव आरोग्य हीटमॅप',
    selectLanguage: 'भाषा निवडा',
    language: 'भाषा',
    emergencySos: 'आणीबाणी SOS',
    dashboard: 'डॅशबोर्ड',
  },

  gu: {
    back: 'પાછળ',
    appName: 'સેહત સાથી',
    getStarted: 'શરૂ કરો',
    voiceTriage: '🎤 અવાજ ટ્રાયેજ',
    speakSymptoms: 'તમારા લક્ષણો બોલો',
    tapToSpeak: 'બોલવા માટે ટેપ કરો',
    listening: 'સાંભળી રહ્યા છે...',
    selectLanguage: 'ભાષા પસંદ કરો',
    language: 'ભાષા',
    dashboard: 'ડેશબોર્ડ',
  },

  kn: {
    back: 'ಹಿಂದೆ',
    appName: 'ಸೆಹತ್ ಸಾಥಿ',
    getStarted: 'ಪ್ರಾರಂಭಿಸಿ',
    voiceTriage: '🎤 ಧ್ವನಿ ಟ್ರಯಾಜ್',
    speakSymptoms: 'ನಿಮ್ಮ ಲಕ್ಷಣಗಳನ್ನು ಹೇಳಿ',
    tapToSpeak: 'ಮಾತನಾಡಲು ಟ್ಯಾಪ್ ಮಾಡಿ',
    listening: 'ಕೇಳುತ್ತಿದ್ದೆ...',
    selectLanguage: 'ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ',
    language: 'ಭಾಷೆ',
    dashboard: 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
  },
};

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => localStorage.getItem('ss_lang') || 'en');

  const changeLang = useCallback((code) => {
    setLang(code);
    localStorage.setItem('ss_lang', code);
  }, []);

  const t = useCallback((key, ...args) => {
    let text = translations[lang]?.[key] || translations.en[key] || key;
    args.forEach((val, i) => { text = text.replace(`{${i}}`, val); });
    return text;
  }, [lang]);

  const currentLang = LANGUAGES.find(l => l.code === lang) || LANGUAGES[0];

  return (
    <LanguageContext.Provider value={{ lang, changeLang, t, currentLang, LANGUAGES }}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLanguage = () => useContext(LanguageContext);
